services:
  ollama:
    build:
      context: ./docker-ollama
      dockerfile: Dockerfile
    container_name: ollama
    ports:
      - "11434:11434"
  websearch:
    build:
       context: ./docker-agentic-web-search
       dockerfile: Dockerfile
    container_name: websearch
    ports:
       - "8008:8008"
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=ics'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'